language: python

branches:
    only:
        - master
        - test0929-1
        - test0929

env:
    - var=units
#    - var=intergrations

#matrix:
#    include:
#        - python: 2.6
#          env: {TOX_ENV: py26}
#        - python: 2.7
#          env: {TOX_ENV: py27, COVERAGE: 1}

install:
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install -qq bash-completion mp3gain
    - travis_retry pip install tox sphinx
    - "[ ! -z $COVERAGE ] && pip install coveralls || true"
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "hello travis, hello github." || false'

#script: tox -e $TOX_ENV
script:
    - sh ex1.sh
    - sh ex2.sh
    - "echo $var"

# coveralls.io reporting, using https://github.com/coagulant/coveralls-python
# Only report coverage for one version.
after_success:
    - "[ ! -z $COVERAGE ] && coveralls || true"

#notifications:
#    email: "yygoto0515@163.com"
    #irc:
        #channels:
        #    - "irc.freenode.org#beets"
        #use_notice: true
        #skip_join: true
    #    on_success: change
    #    on_failure: always
    #    just for test
